### ISSUE TITLE
additional_emails field in UpdateCustomerRequest

### ISSUE THREAD

**Issue by sjmiller609** [MaterializeInc/rust-orb-billing#30]
https://docs.withorb.com/reference/update-customer-external-id

**Comment by benesch** [comment]
PRs welcome!

**Comment by sjmiller609** [comment]
https://github.com/MaterializeInc/rust-orb-billing/pull/31

**Comment by arusahni** [comment]
@sjmiller609 thanks for the PR! This is in the v0.9.0 release that I just published to crates.io.
