### ISSUE TITLE
Not seeing `portal_url` on the latest version (0.10.0)

### ISSUE THREAD

**Issue by DarrenBaldwin07** [MaterializeInc/rust-orb-billing#40]
It looks like there was a PR merged for this around ~2weeks ago but I am not seeing `portal_url` on the `Customer` struct in the latest release https://github.com/MaterializeInc/rust-orb-billing/blob/2faa79d8374af0b8090fd46073d4040716d70fc6/src/client/customers.rs#L187

**Comment by arusahni** [comment]
@DarrenBaldwin07 we haven't yet cut a new release so this is just on `main`. Is this something you need at the moment, or just a check-in?

**Comment by DarrenBaldwin07** [comment]
> @DarrenBaldwin07 we haven't yet cut a new release so this is just on `main`. Is this something you need at the moment, or just a check-in?

Yes, it would be nice to have this asap :)

**Comment by arusahni** [comment]
Gotcha. I'll get this release out tomorrow.

**Comment by arusahni** [comment]
v0.11.0 has been released. It contains the `portal_url` field.
